[project]
name = "fastapi-study"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi==0.115.6",
    "uvicorn==0.32.1",
]

[dependency-groups]
dev = [
    "ruff==0.8.2",
]

[tool.ruff]
target-version = "py313"
